
only:
  - main

stages:
  - build
  - deploy

build-job:
  stage: build
  cache:
    key: node_modules
    paths:
      - node_modules/
  image: node:16.14.0
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - node -v
    - npm -v
    - yarn -v
    - yarn
    - yarn build
  artifacts:
    paths:
      - "dist/"

deploy-job:
  stage: deploy
  before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  script:
    - ls
    - echo "${SSH_KEY}"
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r . ${USERNAME}@${HOST}:/home/www

