stages:
  - build
  - deploy
build-job:
  stage: build
  only:
    - main
  cache:
    key: 
      files: 
        - package-lock.json
        - yarn.lock
    paths:
      - node_modules/
  image: node:16.14.0
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - node -v
    - npm -v
    - yarn -v
    - yarn
    - yarn build
  artifacts:
    paths:
      - "dist/"
deploy-job:
  stage: deploy
  only:
    - main
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ls
    - echo "${SSH_KEY}"
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r . ${USERNAME}@${HOST}:/home/www

