
stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:16.14.0
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - node -v
    - npm -v
    - yarn -v
    - yarn
    - yarn build
  artifacts:
    paths:
      - "dist/"

deploy-job:
  stage: deploy
  script:
    - ls
